name: meu_imc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
google_fonts: ^3.0.1
shared_preferences: ^2.2.1
path_provider:  ^2.0.11
sqflite: ^2.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
